module.exports = {
    // Playback
    pause : require('./playback/plex.pause'),
	play : require('./playBack/plex.play'),
	stop : require('./playBack/plex.stop'),
	rewind : require('./playBack/plex.rewind'),
    fastForward : require('./playBack/plex.fastForward'),
    stepForward : require('./playBack/plex.stepForward'),
    bigStepForward : require('./playBack/plex.bigStepForward'),
    stepBack : require('./playBack/plex.stepBack'),
    bigStepBack : require('./playback/plex.bigStepBack'),
    skipNext : require('./playback/plex.skipNext'),
    skipPrevious : require('./playback/plex.skipPrevious'),
    // Navigation
    moveUp : require('./navigation/plex.moveUp'),
    moveDown : require('./navigation/plex.moveDown'),
    moveLeft : require('./navigation/plex.moveLeft'),
    moveRight : require('./navigation/plex.moveRight'),
    pageUp : require('./navigation/plex.pageUp'),
    pageDown : require('./navigation/plex.pageDown'),
    nextLetter : require('./navigation/plex.nextLetter'),
    previousLetter : require('./navigation/plex.previousLetter'),
    select : require('./navigation/plex.select'),
    back : require('./navigation/plex.back'),
    contextMenu : require('./navigation/plex.contextMenu'),
    toggleOSD : require('./navigation/plex.toggleOSD'),
    // Currently
    playing : require('./plex.playing'),
    paused : require('./plex.paused'),
};